name: Publish PowerShell module

on:
  release:
    types: [created]

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Import module
        shell: pwsh
        run: Import-Module ./ -Force

      - name: Publish module
        env:
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
        shell: pwsh
        run: Publish-Module -Path ./ -NuGetApiKey $env:NUGET_KEY -Verbose