name: Publish PowerShell module

on:
  release:
    types: [created]

jobs:
  publish-to-gallery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - name: Install dependencies
      #   shell: pwsh
      #   run: | 
      #     Install-Module -Name Microsoft.Graph -Force
      #     Install-Module -Name PnP.PowerShell -Force
      #     Install-Module -Name ExchangeOnlineManagement -Force
      - name: Publish
        env:
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
        shell: pwsh
        run: Publish-Module -Path ./ -NuGetApiKey $env:NUGET_KEY -Verbose