name: Publish PowerShell module

on:
  release:
    types: [created]

jobs:
  publish-to-gallery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        shell: pwsh
        run: | 
          Install-Module -Name Microsoft.Graph.Authentication -MinimumVersion 1.25.0 -Force
          Install-Module -Name Microsoft.Graph.Users -MinimumVersion 1.25.0 -Force
          Install-Module -Name Microsoft.Graph.Identity.DirectoryManagement -MinimumVersion 1.25.0 -Force
          Install-Module -Name Microsoft.Graph.DeviceManagement.Enrolment -MinimumVersion 1.25.0 -Force
          Install-Module -Name Microsoft.Graph.Identity.SignIns -MinimumVersion 1.25.0 -Force
          Install-Module -Name Microsoft.Graph.Devices.CorporateManagement -MinimumVersion 1.25.0 -Force
          Install-Module -Name PnP.PowerShell -MinimumVersion 2.1.1 -Force
          Install-Module -Name ExchangeOnlineManagement -MinimumVersion 3.1.0 -Force
          Install-Module -Name DnsClient-PS -MinimumVersion 1.1.0 -Force
      - name: Publish
        env:
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
        shell: pwsh
        run: Publish-Module -Path ./ -NuGetApiKey $env:NUGET_KEY -Verbose